version: '3.4'

x-var: &AEROSPIKE_NAMESPACE session-provider

services:
  middleware:
    container_name: middleware
    depends_on: 
      aerospike:
        condition: service_healthy
    build: 
      context: .
      dockerfile: src/FarabixoMiddleware/Dockerfile
    environment:
      Aerospike:Namespace: *AEROSPIKE_NAMESPACE
      Aerospike:Set: Beta
      Aerospike:Hosts: aerospike:3000
    ports:
      - 7000:80
  
  aerospike:
    image: aerospike/aerospike-server
    attach: false
    environment:
      NAMESPACE: *AEROSPIKE_NAMESPACE
    logging:
      driver: none
    healthcheck:
      test: asinfo -v STATUS
      interval: 1s
      timeout: 1s
      retries: 20